# Generated by Django 2.1.2 on 2019-03-14 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0006_auto_20190314_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
