# Generated by Django 2.1.2 on 2019-03-18 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0013_auto_20190314_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
