# Generated by Django 2.1.2 on 2019-03-18 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0014_auto_20190318_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
