# Generated by Django 2.1.2 on 2019-03-18 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('politics', '0015_auto_20190318_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='ups', to=settings.AUTH_USER_MODEL),
        ),
    ]
