# Generated by Django 2.1.2 on 2019-03-18 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0016_debate_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
