# Generated by Django 2.1.2 on 2019-03-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190318_1710'),
        ('politics', '0019_remove_debate_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='login.UserProfile'),
        ),
    ]
