# Generated by Django 2.1.2 on 2019-03-26 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0020_debate_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
